""" plants  table

Revision ID: 31443ad4aedf
Revises: 339397c4a2b6
Create Date: 2024-01-12 21:27:34.676594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31443ad4aedf'
down_revision = '339397c4a2b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
